
source 'https://github.com/CocoaPods/Specs.git'

target 'TC168' do
platform :ios, '8.0'
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/SMS'
pod 'UMengUShare/UI’
pod 'CodePush', :path => '../node_modules/react-native-code-push'

pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.2'
pod 'MBProgressHUD', '~> 1.0.0'


pod 'React', path: '../node_modules/react-native', subspecs: [
'ART',
]

end
